// Generated by gencpp from file morai_msgs/VehicleSpecDetails.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_VEHICLESPECDETAILS_H
#define MORAI_MSGS_MESSAGE_VEHICLESPECDETAILS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <morai_msgs/VehicleSpecDetail.h>

namespace morai_msgs
{
template <class ContainerAllocator>
struct VehicleSpecDetails_
{
  typedef VehicleSpecDetails_<ContainerAllocator> Type;

  VehicleSpecDetails_()
    : header()
    , specs()  {
    }
  VehicleSpecDetails_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , specs(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::morai_msgs::VehicleSpecDetail_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::morai_msgs::VehicleSpecDetail_<ContainerAllocator> >::other >  _specs_type;
  _specs_type specs;





  typedef boost::shared_ptr< ::morai_msgs::VehicleSpecDetails_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::VehicleSpecDetails_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleSpecDetails_

typedef ::morai_msgs::VehicleSpecDetails_<std::allocator<void> > VehicleSpecDetails;

typedef boost::shared_ptr< ::morai_msgs::VehicleSpecDetails > VehicleSpecDetailsPtr;
typedef boost::shared_ptr< ::morai_msgs::VehicleSpecDetails const> VehicleSpecDetailsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::VehicleSpecDetails_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::VehicleSpecDetails_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::VehicleSpecDetails_<ContainerAllocator1> & lhs, const ::morai_msgs::VehicleSpecDetails_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.specs == rhs.specs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::VehicleSpecDetails_<ContainerAllocator1> & lhs, const ::morai_msgs::VehicleSpecDetails_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::VehicleSpecDetails_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::VehicleSpecDetails_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::VehicleSpecDetails_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::VehicleSpecDetails_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::VehicleSpecDetails_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::VehicleSpecDetails_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::VehicleSpecDetails_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c8a38f8f7239dedd3095eb3a43a095b9";
  }

  static const char* value(const ::morai_msgs::VehicleSpecDetails_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc8a38f8f7239deddULL;
  static const uint64_t static_value2 = 0x3095eb3a43a095b9ULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::VehicleSpecDetails_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/VehicleSpecDetails";
  }

  static const char* value(const ::morai_msgs::VehicleSpecDetails_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::VehicleSpecDetails_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# frame and time stamp\n"
"Header header\n"
"\n"
"# vehicle spec list\n"
"VehicleSpecDetail[] specs\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: morai_msgs/VehicleSpecDetail\n"
"# frame and time stamp\n"
"Header header\n"
"\n"
"# vehicle name\n"
"string vehicle_name\n"
"\n"
"# vehicle spec\n"
"float32 length\n"
"float32 width\n"
"float32 height\n"
"\n"
"float32 wheelbase\n"
"float32 front_overhang\n"
"float32 rear_overhang\n"
;
  }

  static const char* value(const ::morai_msgs::VehicleSpecDetails_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::VehicleSpecDetails_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.specs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleSpecDetails_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::VehicleSpecDetails_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::VehicleSpecDetails_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "specs[]" << std::endl;
    for (size_t i = 0; i < v.specs.size(); ++i)
    {
      s << indent << "  specs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::morai_msgs::VehicleSpecDetail_<ContainerAllocator> >::stream(s, indent + "    ", v.specs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_VEHICLESPECDETAILS_H
