(cl:in-package cardriver-msg)
(cl:export '(CAR_CONNECTED-VAL
          CAR_CONNECTED
          STEER_DEGREE-VAL
          STEER_DEGREE
          STEER_RAW-VAL
          STEER_RAW
          STEER_LIMIT_LEFT-VAL
          STEER_LIMIT_LEFT
          STEER_LIMIT_CENTER-VAL
          STEER_LIMIT_CENTER
          STEER_LIMIT_RIGHT-VAL
          STEER_LIMIT_RIGHT
          ROTOR_HALL-VAL
          ROTOR_HALL
          ROTOR_HALL_L-VAL
          ROTOR_HALL_L
          ROTOR_HALL_R-VAL
          ROTOR_HALL_R
          VOLTAGE-VAL
          VOLTAGE
          CURRENT_CHARGING-VAL
          CURRENT_CHARGING
          CURRENT_DISCHARGING-VAL
          CURRENT_DISCHARGING
          DRV_TEMPERATURE-VAL
          DRV_TEMPERATURE
          CAR_VECTOR-VAL
          CAR_VECTOR
          CAR_LAMP-VAL
          CAR_LAMP
          CAR_SIGNAL-VAL
          CAR_SIGNAL
          CAR_SOLIDBRK-VAL
          CAR_SOLIDBRK
          EMBED_CUSTOM_A-VAL
          EMBED_CUSTOM_A
          EMBED_CUSTOM_B-VAL
          EMBED_CUSTOM_B
))